Tracker:AddLocations("locations/Overworld.jsonc")
Tracker:AddLocations("locations/Things Betwixt.jsonc")
Tracker:AddLocations("locations/Majula.jsonc")
Tracker:AddLocations("locations/The Pit.jsonc")
Tracker:AddLocations("locations/Forest of the Fallen Giants.jsonc")
Tracker:AddLocations("locations/Huntmans Copse.jsonc")
Tracker:AddLocations("locations/Heides Tower of Flame.jsonc")
Tracker:AddLocations("locations/Shaded Woods.jsonc")
Tracker:AddLocations("locations/Aldias Keep.jsonc")
Tracker:AddLocations("locations/Belfry Luna.jsonc")
Tracker:AddLocations("locations/Iron Keep.jsonc")
Tracker:AddLocations("locations/Belfry Sol.jsonc")
Tracker:AddLocations("locations/Black Gulch.jsonc")
Tracker:AddLocations("locations/Grave of Saints.jsonc")
Tracker:AddLocations("locations/Cathedral of Blue.jsonc")
Tracker:AddLocations("locations/Sinners Rise.jsonc")
Tracker:AddLocations("locations/Dragon Aerie.jsonc")
Tracker:AddLocations("locations/Dragon Shrine.jsonc")

